Correct after-period spacing and Type Systems link
LispCookbook/cl-cookbook pull request #420
Opened 2021-11-02 11:02 UTC by dpflug

2021-11-03 15:34 UTC, vindarel requested changes

2021-11-03 15:34 UTC, vindarel commented on performance.md
> +As mentioned in the [*Type System*](type.html) chapter, Lisp has a relatively
At the bottom of the md page, there is this ref: `[sec:type]: #type`. You didn't edit it right? Either rm or edit it (but better use the reference as it is done in this page for all the links).

2021-11-03 15:36 UTC, vindarel commented
Hello, thanks for the PR.

All the after-period spacing, it's only for convenience in the markdown file, the extra spacing didn't impact the final html, right? This extra-spacing might appear again, it probably comes from someone's/my emacs M-q fill-paragraph.

2021-11-03 18:24 UTC, dpflug commented
As for the after-period spacing, I only bothered because there were paragraphs where they were mixed. I assumed it was manually input. I can remove them if preferred.

2021-11-30 14:33 UTC, vindarel commented
Hello, there were changes on the alive page, now there are conflicts, if you could fix them… thanks.

2021-12-06 05:55 UTC, dpflug commented
Is there anything else needed?

2021-12-06 17:58 UTC, merged

2021-12-06 17:58 UTC, vindarel commented
Thank you!